[package]
name = "kinakaze-v2-libcuda"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "kinakaze_libcuda"
crate-type = ["dylib"]

[dependencies]
kinakaze-runtime.workspace = true
kinakaze-tls.workspace = true
kinakaze-vfs.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_System_LibraryLoader"] }
