[package]
name = "kinakaze-v2-rootfs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"

[lints]
workspace = true
