//! `vkGetInstanceProcAddr` and `vkGetDeviceProcAddr`.
//!
//! These two cannot be generated by `passthrough!`, because they are the one
//! place where a Vulkan call *returns* a function pointer. Forwarding them
//! unchanged would hand the guest a host address, which the guest would then call
//! with the System V convention against a Windows x64 function — arguments in the
//! wrong registers, no shadow space, and a crash somewhere inside a driver with
//! nothing in the backtrace to explain it.
//!
//! So they are answered from this crate's own table. A name that this library
//! wraps yields *our* thunk; anything else yields null.
//!
//! ## Why null, and not the host pointer
//!
//! Returning the host address for an unwrapped name would look more capable and
//! be strictly worse: the guest cannot call it, so the only question is whether it
//! finds out by getting null or by crashing. Null is also the answer Vulkan
//! defines for "not available", and it is what every extension check is written
//! against — `if (!pfn) { /* fall back */ }`. A guest that checks gets a correct
//! answer and can take its fallback path.
//!
//! The same reasoning drives the `present()` test on every lookup: a name this
//! crate wraps but the *host loader* does not export also yields null, because
//! claiming an entry point that would abort on first call is the same lie in a
//! different place.
//!
//! ## The null-instance rule
//!
//! `vkGetInstanceProcAddr(NULL, name)` is legal for exactly four names, which are
//! the ones a program needs before it has an instance to ask with. Any other name
//! must return null when the instance is null. Honouring this matters because a
//! loader that answers everything for a null instance lets a guest accidentally
//! depend on being able to skip instance creation, which then fails on a real
//! Linux loader.

use core::ffi::{CStr, c_char, c_void};

use crate::types::{VkDevice, VkInstance};

/// The entry points a program may resolve before it has an instance.
///
/// `vkEnumerateInstanceVersion` is the 1.1 addition to this set; the other three
/// have been global since 1.0.
const GLOBAL_ENTRY_POINTS: &[&str] = &[
    "vkCreateInstance",
    "vkEnumerateInstanceExtensionProperties",
    "vkEnumerateInstanceLayerProperties",
    "vkEnumerateInstanceVersion",
];

/// Commands implemented outside the generated loader-export and extension
/// tables.  Keeping this list next to dispatch makes completeness testable:
/// groups + generated extensions + these translations must equal the registry.
#[cfg(test)]
pub(crate) const INTERCEPTED_ENTRY_POINTS: &[&str] = &[
    "vkGetInstanceProcAddr",
    "vkGetDeviceProcAddr",
    "vkCreateInstance",
    "vkCreateDevice",
    "vkEnumerateInstanceExtensionProperties",
    "vkCreateDebugUtilsMessengerEXT",
    "vkCreateDebugReportCallbackEXT",
    "vkCreateXlibSurfaceKHR",
    "vkCreateXcbSurfaceKHR",
    "vkCreateWaylandSurfaceKHR",
    "vkGetPhysicalDeviceXcbPresentationSupportKHR",
    "vkGetPhysicalDeviceXlibPresentationSupportKHR",
    "vkGetPhysicalDeviceWaylandPresentationSupportKHR",
];

/// Finds the thunk for `name` across every declared group.
///
/// Each group's `lookup` already applies the host-presence test, so a `Some` here
/// means both that this crate wraps the name and that the host can service it.
fn static_thunk(name: &str) -> Option<usize> {
    // `vkGetInstanceProcAddr` and `vkGetDeviceProcAddr` are answered from this
    // module rather than from a group, so they are matched first. A guest is
    // entitled to ask for them by name — it is how a layer chains to the next
    // one down — and it must receive our own address, not the host's.
    match name {
        "vkGetInstanceProcAddr" => {
            return Some(vkGetInstanceProcAddr as *const () as usize);
        }
        "vkGetDeviceProcAddr" => {
            return Some(vkGetDeviceProcAddr as *const () as usize);
        }
        "vkCreateInstance" => {
            return Some(crate::wsi_compat::vkCreateInstance as *const () as usize);
        }
        "vkCreateDevice" => {
            return crate::device_callbacks::host_present()
                .then_some(crate::device_callbacks::vkCreateDevice as *const () as usize);
        }
        "vkEnumerateInstanceExtensionProperties" => {
            return Some(
                crate::wsi_compat::vkEnumerateInstanceExtensionProperties as *const () as usize,
            );
        }
        "vkCreateDebugUtilsMessengerEXT" => {
            return Some(
                crate::debug_callbacks::vkCreateDebugUtilsMessengerEXT as *const () as usize,
            );
        }
        "vkCreateDebugReportCallbackEXT" => {
            return Some(
                crate::debug_callbacks::vkCreateDebugReportCallbackEXT as *const () as usize,
            );
        }
        "vkCreateXlibSurfaceKHR" => {
            return Some(crate::wsi_compat::vkCreateXlibSurfaceKHR as *const () as usize);
        }
        "vkCreateXcbSurfaceKHR" => {
            return Some(crate::wsi_compat::vkCreateXcbSurfaceKHR as *const () as usize);
        }
        "vkCreateWaylandSurfaceKHR" => {
            return Some(crate::wsi_compat::vkCreateWaylandSurfaceKHR as *const () as usize);
        }
        "vkGetPhysicalDeviceXcbPresentationSupportKHR" => {
            return Some(
                crate::wsi_compat::vkGetPhysicalDeviceXcbPresentationSupportKHR as *const ()
                    as usize,
            );
        }
        "vkGetPhysicalDeviceXlibPresentationSupportKHR" => {
            return Some(
                crate::wsi_compat::vkGetPhysicalDeviceXlibPresentationSupportKHR as *const ()
                    as usize,
            );
        }
        "vkGetPhysicalDeviceWaylandPresentationSupportKHR" => {
            return Some(
                crate::wsi_compat::vkGetPhysicalDeviceWaylandPresentationSupportKHR as *const ()
                    as usize,
            );
        }
        "vkGetPhysicalDeviceQueueFamilyProperties" => {
            return Some(
                crate::wsi_compat::get_physical_device_queue_family_properties as *const ()
                    as usize,
            );
        }
        "vkGetPhysicalDeviceQueueFamilyProperties2" => {
            return Some(
                crate::wsi_compat::get_physical_device_queue_family_properties2 as *const ()
                    as usize,
            );
        }
        _ => {}
    }

    crate::groups::lookup(name)
}

/// Reads a C string argument, rejecting null and non-UTF-8.
///
/// Vulkan entry-point names are ASCII, so a name that is not valid UTF-8 is not a
/// Vulkan entry point and null is the right answer.
///
/// # Safety
///
/// `name` must be null or point to a NUL-terminated string.
unsafe fn entry_point_name(name: *const c_char) -> Option<&'static str> {
    if name.is_null() {
        return None;
    }
    // SAFETY: the caller guarantees a NUL-terminated string; Vulkan requires the
    // name to remain valid for the duration of the call.
    unsafe { CStr::from_ptr(name) }.to_str().ok()
}

/// `vkGetInstanceProcAddr`.
///
/// # Safety
///
/// `name` must be null or a NUL-terminated string. `instance` must be null or a
/// live `VkInstance`.
#[unsafe(export_name = "kinakaze_engine_libvulkan_vkGetInstanceProcAddr")]
pub unsafe extern "sysv64" fn vkGetInstanceProcAddr(
    instance: VkInstance,
    name: *const c_char,
) -> *const c_void {
    // SAFETY: forwarded from the caller under the same contract.
    let Some(name) = (unsafe { entry_point_name(name) }) else {
        return core::ptr::null();
    };

    // Before an instance exists, only the global entry points may be resolved.
    if instance.is_null() && !GLOBAL_ENTRY_POINTS.contains(&name) {
        return core::ptr::null();
    }

    let resolved = match static_thunk(name) {
        some @ Some(_) => some,
        None if !instance.is_null() => crate::generated_extensions::lookup_instance(instance, name),
        None => None,
    };
    match resolved {
        Some(address) => address as *const c_void,
        None => core::ptr::null(),
    }
}

/// `vkGetDeviceProcAddr`.
///
/// Vulkan permits this to return null for anything that is not a device-level
/// function, and requires null for an unknown name. Device-level dispatch is not
/// distinguished from instance-level here: the returned thunk resolves the host
/// address by name through the loader, which performs the same dispatch a driver
/// would. The cost is that an instance-level name asked for through this entry
/// point is answered rather than refused — permitted, but worth stating.
///
/// # Safety
///
/// `name` must be null or a NUL-terminated string. `device` must be null or a live
/// `VkDevice`.
#[unsafe(export_name = "kinakaze_engine_libvulkan_vkGetDeviceProcAddr")]
pub unsafe extern "sysv64" fn vkGetDeviceProcAddr(
    device: VkDevice,
    name: *const c_char,
) -> *const c_void {
    // SAFETY: forwarded from the caller under the same contract.
    let Some(name) = (unsafe { entry_point_name(name) }) else {
        return core::ptr::null();
    };
    if device.is_null() {
        return core::ptr::null();
    }
    let resolved = match static_thunk(name) {
        some @ Some(_) => some,
        None => crate::generated_extensions::lookup_device(device, name),
    };
    match resolved {
        Some(address) => address as *const c_void,
        None => core::ptr::null(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::CString;

    fn resolve(instance: VkInstance, name: &str) -> *const c_void {
        let name = CString::new(name).expect("test name has no interior NUL");
        // SAFETY: `name` is a live NUL-terminated string for the call.
        unsafe { vkGetInstanceProcAddr(instance, name.as_ptr()) }
    }

    /// A fabricated non-null instance. These entry points only test the pointer
    /// against null; they never dereference it, which is what makes this safe and
    /// lets the dispatch logic be tested without creating a real instance.
    fn any_instance() -> VkInstance {
        0x1000_usize as VkInstance
    }

    /// The core guarantee: a wrapped name resolves to an address inside *this*
    /// module's image, never to the host loader's.
    ///
    /// Compares against the host address directly, because returning that pointer
    /// is the specific bug this module exists to prevent and it would otherwise
    /// look like success.
    #[test]
    fn a_wrapped_name_yields_our_thunk_not_the_hosts() {
        if !crate::host::loader_present() {
            eprintln!("skipped: no host Vulkan loader on this machine");
            return;
        }
        let ours = resolve(any_instance(), "vkDeviceWaitIdle");
        assert!(!ours.is_null(), "vkDeviceWaitIdle should be wrapped");
        let host = crate::host::symbol("vkDeviceWaitIdle").expect("host exports it");
        assert_ne!(
            ours as usize, host,
            "returned the host address, which the guest would call with the wrong ABI"
        );
    }

    /// An unknown name must be null rather than anything else.
    #[test]
    fn an_unknown_name_is_null() {
        assert!(resolve(any_instance(), "vkNotARealFunction").is_null());
    }

    /// Null and non-UTF-8 names must not panic across the ABI boundary.
    #[test]
    fn a_null_name_is_null() {
        // SAFETY: null is explicitly handled.
        assert!(unsafe { vkGetInstanceProcAddr(any_instance(), core::ptr::null()) }.is_null());
    }

    /// The four global entry points are resolvable without an instance.
    #[test]
    fn the_global_entry_points_need_no_instance() {
        if !crate::host::loader_present() {
            eprintln!("skipped: no host Vulkan loader on this machine");
            return;
        }
        for name in ["vkCreateInstance", "vkEnumerateInstanceExtensionProperties"] {
            assert!(
                !resolve(core::ptr::null_mut(), name).is_null(),
                "{name} must resolve with a null instance"
            );
        }
    }

    /// Anything else must not be, or a guest could come to depend on skipping
    /// instance creation and then fail on a real loader.
    #[test]
    fn other_entry_points_need_an_instance() {
        assert!(
            resolve(core::ptr::null_mut(), "vkDeviceWaitIdle").is_null(),
            "a non-global entry point must not resolve with a null instance"
        );
    }

    /// Asking for the dispatch roots themselves must yield our own addresses;
    /// this is how a layer chains downward.
    #[test]
    fn the_dispatch_roots_resolve_to_themselves() {
        let instance_root = resolve(any_instance(), "vkGetInstanceProcAddr");
        assert_eq!(
            instance_root as usize,
            vkGetInstanceProcAddr as *const () as usize
        );
        let device_root = resolve(any_instance(), "vkGetDeviceProcAddr");
        assert_eq!(
            device_root as usize,
            vkGetDeviceProcAddr as *const () as usize
        );
    }

    #[test]
    fn linux_wsi_queries_resolve_to_translation_thunks() {
        for name in [
            "vkGetPhysicalDeviceXcbPresentationSupportKHR",
            "vkGetPhysicalDeviceXlibPresentationSupportKHR",
            "vkGetPhysicalDeviceWaylandPresentationSupportKHR",
        ] {
            assert!(!resolve(any_instance(), name).is_null(), "{name}");
        }
    }

    #[test]
    fn promoted_extension_names_have_dedicated_abi_thunks() {
        for alias in [
            "vkCmdPipelineBarrier2KHR",
            "vkCmdBeginRenderingKHR",
            "vkCmdPushDescriptorSetKHR",
        ] {
            assert!(crate::generated_extensions::contains(alias), "{alias}");
        }
    }

    /// `vkGetDeviceProcAddr` with a null device is null.
    #[test]
    fn a_null_device_resolves_nothing() {
        let name = CString::new("vkDeviceWaitIdle").expect("no interior NUL");
        // SAFETY: `name` is live and NUL-terminated; null device is handled.
        let result = unsafe { vkGetDeviceProcAddr(core::ptr::null_mut(), name.as_ptr()) };
        assert!(result.is_null());
    }
}
