//! CUDA driver signatures. Version anchors are from CUDA 12.8 cudaTypedefs.h.
//! Pointers, size_t and opaque handles have the same width in both x86-64 ABIs.
use crate::*;

crate::cuda_api! {
    [cuInit, 2000, 0] fn cuInit(Flags: u32);
    [cuDriverGetVersion, 2020, 0] fn cuDriverGetVersion(driverVersion: *mut i32);
    [cuGetErrorName, 6000, 0] fn cuGetErrorName(error: CuResult, pStr: *mut *const c_char);
    [cuGetErrorString, 6000, 0] fn cuGetErrorString(error: CuResult, pStr: *mut *const c_char);
    [cuDeviceGetCount, 2000, 0] fn cuDeviceGetCount(count: *mut i32);
    [cuDeviceGet, 2000, 0] fn cuDeviceGet(device: *mut CuDevice, ordinal: i32);
    [cuDeviceGetName, 2000, 0] fn cuDeviceGetName(name: *mut c_char, len: i32, dev: CuDevice);
    [cuDeviceGetUuid, 9020, 0] fn cuDeviceGetUuid(uuid: *mut CuUuid, dev: CuDevice);
    [cuDeviceGetUuid, 11040, 0] fn cuDeviceGetUuid_v2(uuid: *mut CuUuid, dev: CuDevice);
    [cuDeviceGetAttribute, 2000, 0] fn cuDeviceGetAttribute(pi: *mut i32, attrib: i32, dev: CuDevice);
    [cuDeviceTotalMem, 3020, 0] fn cuDeviceTotalMem_v2(bytes: *mut usize, dev: CuDevice);
    [cuDeviceComputeCapability, 2000, 0] fn cuDeviceComputeCapability(major: *mut i32, minor: *mut i32, dev: CuDevice);
    [cuDeviceGetPCIBusId, 4010, 0] fn cuDeviceGetPCIBusId(pciBusId: *mut c_char, len: i32, dev: CuDevice);
    [cuDeviceGetByPCIBusId, 4010, 0] fn cuDeviceGetByPCIBusId(dev: *mut CuDevice, pciBusId: *const c_char);
    [cuDevicePrimaryCtxRetain, 7000, 0] fn cuDevicePrimaryCtxRetain(pctx: *mut CuContext, dev: CuDevice);
    [cuDevicePrimaryCtxRelease, 7000, 0] fn cuDevicePrimaryCtxRelease(dev: CuDevice);
    [cuDevicePrimaryCtxRelease, 11000, 0] fn cuDevicePrimaryCtxRelease_v2(dev: CuDevice);
    [cuDevicePrimaryCtxReset, 7000, 0] fn cuDevicePrimaryCtxReset(dev: CuDevice);
    [cuDevicePrimaryCtxReset, 11000, 0] fn cuDevicePrimaryCtxReset_v2(dev: CuDevice);
    [cuDevicePrimaryCtxSetFlags, 7000, 0] fn cuDevicePrimaryCtxSetFlags(dev: CuDevice, flags: u32);
    [cuDevicePrimaryCtxSetFlags, 11000, 0] fn cuDevicePrimaryCtxSetFlags_v2(dev: CuDevice, flags: u32);
    [cuDevicePrimaryCtxGetState, 7000, 0] fn cuDevicePrimaryCtxGetState(dev: CuDevice, flags: *mut u32, active: *mut i32);
    [cuCtxCreate, 3020, 0] fn cuCtxCreate_v2(pctx: *mut CuContext, flags: u32, dev: CuDevice);
    [cuCtxCreate, 11040, 0] fn cuCtxCreate_v3(pctx: *mut CuContext, paramsArray: *mut CuExecAffinityParam, numParams: i32, flags: u32, dev: CuDevice);
    [cuCtxDestroy, 4000, 0] fn cuCtxDestroy_v2(ctx: CuContext);
    [cuCtxPushCurrent, 4000, 0] fn cuCtxPushCurrent_v2(ctx: CuContext);
    [cuCtxPopCurrent, 4000, 0] fn cuCtxPopCurrent_v2(pctx: *mut CuContext);
    [cuCtxSetCurrent, 4000, 0] fn cuCtxSetCurrent(ctx: CuContext);
    [cuCtxGetCurrent, 4000, 0] fn cuCtxGetCurrent(pctx: *mut CuContext);
    [cuCtxGetDevice, 2000, 0] fn cuCtxGetDevice(device: *mut CuDevice);
    [cuCtxGetFlags, 7000, 0] fn cuCtxGetFlags(flags: *mut u32);
    [cuCtxSynchronize, 2000, 0] fn cuCtxSynchronize();
    [cuCtxGetApiVersion, 3020, 0] fn cuCtxGetApiVersion(ctx: CuContext, version: *mut u32);
    [cuCtxSetLimit, 3010, 0] fn cuCtxSetLimit(limit: i32, value: usize);
    [cuCtxGetLimit, 3010, 0] fn cuCtxGetLimit(pvalue: *mut usize, limit: i32);
    [cuCtxGetStreamPriorityRange, 5050, 0] fn cuCtxGetStreamPriorityRange(leastPriority: *mut i32, greatestPriority: *mut i32);
    [cuMemAlloc, 3020, 0] fn cuMemAlloc_v2(dptr: *mut CuDevicePtr, bytesize: usize);
    [cuMemFree, 3020, 0] fn cuMemFree_v2(dptr: CuDevicePtr);
    [cuMemGetInfo, 3020, 0] fn cuMemGetInfo_v2(free: *mut usize, total: *mut usize);
    [cuMemAllocHost, 3020, 0] fn cuMemAllocHost_v2(pp: *mut *mut c_void, bytesize: usize);
    [cuMemFreeHost, 2000, 0] fn cuMemFreeHost(p: *mut c_void);
    [cuMemHostAlloc, 2020, 0] fn cuMemHostAlloc(pp: *mut *mut c_void, bytesize: usize, Flags: u32);
    [cuMemHostRegister, 6050, 0] fn cuMemHostRegister_v2(p: *mut c_void, bytesize: usize, Flags: u32);
    [cuMemHostUnregister, 4000, 0] fn cuMemHostUnregister(p: *mut c_void);
    [cuMemHostGetDevicePointer, 3020, 0] fn cuMemHostGetDevicePointer_v2(pdptr: *mut CuDevicePtr, p: *mut c_void, Flags: u32);
    [cuMemHostGetFlags, 2030, 0] fn cuMemHostGetFlags(pFlags: *mut u32, p: *mut c_void);
    [cuMemAllocManaged, 6000, 0] fn cuMemAllocManaged(dptr: *mut CuDevicePtr, bytesize: usize, flags: u32);
    [cuMemcpyHtoD, 3020, 0] fn cuMemcpyHtoD_v2(dstDevice: CuDevicePtr, srcHost: *const c_void, ByteCount: usize);
    [cuMemcpyHtoD, 7000, 2] fn cuMemcpyHtoD_v2_ptds(dstDevice: CuDevicePtr, srcHost: *const c_void, ByteCount: usize);
    [cuMemcpyDtoH, 3020, 0] fn cuMemcpyDtoH_v2(dstHost: *mut c_void, srcDevice: CuDevicePtr, ByteCount: usize);
    [cuMemcpyDtoH, 7000, 2] fn cuMemcpyDtoH_v2_ptds(dstHost: *mut c_void, srcDevice: CuDevicePtr, ByteCount: usize);
    [cuMemcpyDtoD, 3020, 0] fn cuMemcpyDtoD_v2(dstDevice: CuDevicePtr, srcDevice: CuDevicePtr, ByteCount: usize);
    [cuMemcpyDtoD, 7000, 2] fn cuMemcpyDtoD_v2_ptds(dstDevice: CuDevicePtr, srcDevice: CuDevicePtr, ByteCount: usize);
    [cuMemcpyHtoDAsync, 3020, 0] fn cuMemcpyHtoDAsync_v2(dstDevice: CuDevicePtr, srcHost: *const c_void, ByteCount: usize, hStream: CuStream);
    [cuMemcpyHtoDAsync, 7000, 2] fn cuMemcpyHtoDAsync_v2_ptsz(dstDevice: CuDevicePtr, srcHost: *const c_void, ByteCount: usize, hStream: CuStream);
    [cuMemcpyDtoHAsync, 3020, 0] fn cuMemcpyDtoHAsync_v2(dstHost: *mut c_void, srcDevice: CuDevicePtr, ByteCount: usize, hStream: CuStream);
    [cuMemcpyDtoHAsync, 7000, 2] fn cuMemcpyDtoHAsync_v2_ptsz(dstHost: *mut c_void, srcDevice: CuDevicePtr, ByteCount: usize, hStream: CuStream);
    [cuMemcpyDtoDAsync, 3020, 0] fn cuMemcpyDtoDAsync_v2(dstDevice: CuDevicePtr, srcDevice: CuDevicePtr, ByteCount: usize, hStream: CuStream);
    [cuMemcpyDtoDAsync, 7000, 2] fn cuMemcpyDtoDAsync_v2_ptsz(dstDevice: CuDevicePtr, srcDevice: CuDevicePtr, ByteCount: usize, hStream: CuStream);
    [cuMemcpy, 4000, 0] fn cuMemcpy(dst: CuDevicePtr, src: CuDevicePtr, ByteCount: usize);
    [cuMemcpy, 7000, 2] fn cuMemcpy_ptds(dst: CuDevicePtr, src: CuDevicePtr, ByteCount: usize);
    [cuMemcpyAsync, 4000, 0] fn cuMemcpyAsync(dst: CuDevicePtr, src: CuDevicePtr, ByteCount: usize, hStream: CuStream);
    [cuMemcpyAsync, 7000, 2] fn cuMemcpyAsync_ptsz(dst: CuDevicePtr, src: CuDevicePtr, ByteCount: usize, hStream: CuStream);
    [cuMemsetD8, 3020, 0] fn cuMemsetD8_v2(dstDevice: CuDevicePtr, uc: u8, N: usize);
    [cuMemsetD8, 7000, 2] fn cuMemsetD8_v2_ptds(dstDevice: CuDevicePtr, uc: u8, N: usize);
    [cuMemsetD16, 3020, 0] fn cuMemsetD16_v2(dstDevice: CuDevicePtr, us: u16, N: usize);
    [cuMemsetD16, 7000, 2] fn cuMemsetD16_v2_ptds(dstDevice: CuDevicePtr, us: u16, N: usize);
    [cuMemsetD32, 3020, 0] fn cuMemsetD32_v2(dstDevice: CuDevicePtr, ui: u32, N: usize);
    [cuMemsetD32, 7000, 2] fn cuMemsetD32_v2_ptds(dstDevice: CuDevicePtr, ui: u32, N: usize);
    [cuMemsetD8Async, 3020, 0] fn cuMemsetD8Async(dstDevice: CuDevicePtr, uc: u8, N: usize, hStream: CuStream);
    [cuMemsetD8Async, 7000, 2] fn cuMemsetD8Async_ptsz(dstDevice: CuDevicePtr, uc: u8, N: usize, hStream: CuStream);
    [cuMemsetD16Async, 3020, 0] fn cuMemsetD16Async(dstDevice: CuDevicePtr, us: u16, N: usize, hStream: CuStream);
    [cuMemsetD16Async, 7000, 2] fn cuMemsetD16Async_ptsz(dstDevice: CuDevicePtr, us: u16, N: usize, hStream: CuStream);
    [cuMemsetD32Async, 3020, 0] fn cuMemsetD32Async(dstDevice: CuDevicePtr, ui: u32, N: usize, hStream: CuStream);
    [cuMemsetD32Async, 7000, 2] fn cuMemsetD32Async_ptsz(dstDevice: CuDevicePtr, ui: u32, N: usize, hStream: CuStream);
    [cuStreamCreate, 2000, 0] fn cuStreamCreate(phStream: *mut CuStream, Flags: u32);
    [cuStreamCreateWithPriority, 5050, 0] fn cuStreamCreateWithPriority(phStream: *mut CuStream, flags: u32, priority: i32);
    [cuStreamDestroy, 4000, 0] fn cuStreamDestroy_v2(hStream: CuStream);
    [cuStreamSynchronize, 2000, 0] fn cuStreamSynchronize(hStream: CuStream);
    [cuStreamSynchronize, 7000, 2] fn cuStreamSynchronize_ptsz(hStream: CuStream);
    [cuStreamQuery, 2000, 0] fn cuStreamQuery(hStream: CuStream);
    [cuStreamQuery, 7000, 2] fn cuStreamQuery_ptsz(hStream: CuStream);
    [cuStreamWaitEvent, 3020, 0] fn cuStreamWaitEvent(hStream: CuStream, hEvent: CuEvent, Flags: u32);
    [cuStreamWaitEvent, 7000, 2] fn cuStreamWaitEvent_ptsz(hStream: CuStream, hEvent: CuEvent, Flags: u32);
    [cuStreamGetFlags, 5050, 0] fn cuStreamGetFlags(hStream: CuStream, flags: *mut u32);
    [cuStreamGetFlags, 7000, 2] fn cuStreamGetFlags_ptsz(hStream: CuStream, flags: *mut u32);
    [cuStreamGetPriority, 5050, 0] fn cuStreamGetPriority(hStream: CuStream, priority: *mut i32);
    [cuStreamGetPriority, 7000, 2] fn cuStreamGetPriority_ptsz(hStream: CuStream, priority: *mut i32);
    [cuEventCreate, 2000, 0] fn cuEventCreate(phEvent: *mut CuEvent, Flags: u32);
    [cuEventDestroy, 4000, 0] fn cuEventDestroy_v2(hEvent: CuEvent);
    [cuEventRecord, 2000, 0] fn cuEventRecord(hEvent: CuEvent, hStream: CuStream);
    [cuEventRecord, 7000, 2] fn cuEventRecord_ptsz(hEvent: CuEvent, hStream: CuStream);
    [cuEventSynchronize, 2000, 0] fn cuEventSynchronize(hEvent: CuEvent);
    [cuEventQuery, 2000, 0] fn cuEventQuery(hEvent: CuEvent);
    [cuEventElapsedTime, 2000, 0] fn cuEventElapsedTime(pMilliseconds: *mut f32, hStart: CuEvent, hEnd: CuEvent);
    [cuModuleLoadData, 2000, 0] fn cuModuleLoadData(module: *mut CuModule, image: *const c_void);
    [cuModuleLoadDataEx, 2010, 0] fn cuModuleLoadDataEx(module: *mut CuModule, image: *const c_void, numOptions: u32, options: *mut i32, optionValues: *mut *mut c_void);
    [cuModuleLoadFatBinary, 2000, 0] fn cuModuleLoadFatBinary(module: *mut CuModule, fatCubin: *const c_void);
    [cuModuleUnload, 2000, 0] fn cuModuleUnload(hmod: CuModule);
    [cuModuleGetFunction, 2000, 0] fn cuModuleGetFunction(hfunc: *mut CuFunction, hmod: CuModule, name: *const c_char);
    [cuModuleGetGlobal, 3020, 0] fn cuModuleGetGlobal_v2(dptr: *mut CuDevicePtr, bytes: *mut usize, hmod: CuModule, name: *const c_char);
    [cuFuncGetAttribute, 2020, 0] fn cuFuncGetAttribute(pi: *mut i32, attrib: i32, hfunc: CuFunction);
    [cuFuncSetAttribute, 9000, 0] fn cuFuncSetAttribute(hfunc: CuFunction, attrib: i32, value: i32);
    [cuFuncSetCacheConfig, 3000, 0] fn cuFuncSetCacheConfig(hfunc: CuFunction, config: i32);
    [cuLaunchKernel, 4000, 0] fn cuLaunchKernel(f: CuFunction, gridDimX: u32, gridDimY: u32, gridDimZ: u32, blockDimX: u32, blockDimY: u32, blockDimZ: u32, sharedMemBytes: u32, hStream: CuStream, kernelParams: *mut *mut c_void, extra: *mut *mut c_void);
    [cuLaunchKernel, 7000, 2] fn cuLaunchKernel_ptsz(f: CuFunction, gridDimX: u32, gridDimY: u32, gridDimZ: u32, blockDimX: u32, blockDimY: u32, blockDimZ: u32, sharedMemBytes: u32, hStream: CuStream, kernelParams: *mut *mut c_void, extra: *mut *mut c_void);
}
